apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-guide-docs-deploy
  namespace: galileo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-guide-docs-app
      version: 'v1'
  template:
    metadata:
      labels:
        app: developer-guide-docs-app
        version: 'v1'
    spec:
      containers:
      - name: backend
        image: registry.supos.com/galileo/developer-guide-docs:1.2.0
        imagePullPolicy: Always
        ports:
        - name: httpd
          containerPort: 8099

