apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: nacos
data:
  MYSQL_SERVICE_HOST: "rm-bp12a7im5071wu476.mysql.rds.aliyuncs.com"
  MYSQL_SERVICE_PORT: "3306"
  MYSQL_SERVICE_DB_NAME: "nacos"
  MYSQL_SERVICE_USER: "nacos"
  MYSQL_SERVICE_PASSWORD: "G7TT4GXALOoo@t!"