apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: galileo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
      version: 'v1'
  template:
    metadata:
      labels:
        app: accounts
        version: 'v1'
    spec:
      containers:
      - name: backend
        image: registry.supos.com/galileo/accounts-service:1.2.8.RELEASE
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms256m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Dcom.alibaba.nacos.naming.log.level=WARN -Dcom.alibaba.nacos.config.log.level=WARN"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: NACOS_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: nacos-username
        - name: NACOS_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: nacos-password
        - name: NACOS_SERVER_ADDR
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.server-addr
        - name: NACOS_CONFIG_NAMESPACE
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.config.namespace
        - name: NACOS_DISCOVERY_NAMESPACE
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.discovery.namespace
        - name: SPRING_OUTPUT_ANSI_ENABLED
          value: "NEVER"
        ports:
        - name: httpd
          containerPort: 9997
        readinessProbe:
          httpGet:
            path: /management/health
            port: 9997
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /management/health
            port: 9997
          initialDelaySeconds: 120
        securityContext:
          privileged: true
      # securityContext:
        # privileged: true
        # runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000
      terminationGracePeriodSeconds: 0
