apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: galileo
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  type: ClusterIP
  ports:
  - name: http
    port: 9997
    targetPort: 9997