apiVersion: v1
kind: Service
metadata:
  name: instructions-docs
  namespace: galileo
spec:
  selector:
    app: instructions-docs-app
  ports:
    - name: http
      port: 8199
      targetPort: 8199
