apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
  namespace: galileo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps
      version: 'v1'
  template:
    metadata:
      labels:
        app: apps
        version: 'v1'
    spec:
      containers:
      - name: apps
        image: registry.supos.com/galileo/apps-service:1.3.0.RELEASE
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms256m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Dcom.alibaba.nacos.naming.log.level=WARN -Dcom.alibaba.nacos.config.log.level=WARN"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: NACOS_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: nacos-username
        - name: NACOS_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: nacos-password
        - name: NACOS_SERVER_ADDR
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.server-addr
        - name: NACOS_CONFIG_NAMESPACE
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.config.namespace
        - name: NACOS_DISCOVERY_NAMESPACE
          valueFrom:
            configMapKeyRef:
                name: nacos-cm
                key: nacos.discovery.namespace
        # - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
        #   value: "true"
        # - name: JHIPSTER_LOGGING_LOGSTASH_HOST
        #   value: "jhipster-logstash"
        # - name: JHIPSTER_METRICS_LOGS_ENABLED
        #   value: "true"
        # - name: JHIPSTER_METRICS_LOGS_REPORTFREQUENCY
        #   value: "60"
        - name: SPRING_OUTPUT_ANSI_ENABLED
          value: "NEVER"
        ports:
        - name: httpd
          containerPort: 8091
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8091
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8091
          initialDelaySeconds: 120
