apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resources-metrics
  namespace: kube-suite
spec:
  selector:
    matchLabels:
      app: resources
  endpoints:
    - port: http
      interval: 10s
      honorLabels: true
      scheme: http
      path: '/management/prometheus'
  namespaceSelector:
    matchNames:
     - galileo
