apiVersion: v1
kind: Service
metadata:
  name: static-resource
  namespace: galileo
spec:
  selector:
    app: static-resource-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80