apiVersion: v1

kind: Service
metadata:
  name: redis-ha-service
  namespace: boss-redis
  labels:
    app: redis-ha
spec:
  ports:
  - name: redis-svc-port
    protocol: "TCP"
    port: 6379
    targetPort: redis
    nodePort: 30379
  selector:
    app: redis-ha
    release: redis-ha
  type: NodePort
