apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-console-frontend
  namespace: galileo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-console-frontend-app
      version: 'v1'
  template:
    metadata:
      labels:
        app: cloud-console-frontend-app
        version: 'v1'
    spec:
      containers:
      - name: backend
        image: registry.supos.com/galileo/cloud-console-frontend:0.8.5
        imagePullPolicy: Always
        ports:
        - name: httpd
          containerPort: 80
