apiVersion: v1
kind: Service
metadata:
  name: cloud-console-frontend
  namespace: galileo
spec:
  selector:
    app: cloud-console-frontend-app
  ports:
  - name: http
    port: 80
    targetPort: 80
