kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-graylog-multiline-config
  namespace: kube-system
data:
  multiline.conf: |-
    <filter kubernetes.**galileo**>
      @type concat
      key log
      multiline_start_regexp /^[0-9]{4}-[0-9]{2}-[0-9]{2}/
      flush_interval 5
    </filter>
